### PR TITLE
Fix interval

### PR DESCRIPTION
**Pull request by Conaclos**
Hi!
- Fix the syntax of the integer interval
- Add an example of an inspect interval
- Fix a typo ([Ex means Exercice](http://english.stackexchange.com/questions/16197/whats-the-difference-between-e-g-and-ex))

### CODE REVIEW

**Comment by carlfriess** [comment]
Thanks! :smiley: Maybe you could add the difference between `|..|` and `..` since you use `..` in the example?

**Comment by Conaclos** [comment]
Hi! Relevant remarks!
I will take a look at this one in coming days :)

**Comment by Conaclos** [comment]
Is you ok with the last commit?

**Comment by carlfriess** [comment]
Thanks! :smiley:

**Pull request merged**
